### ISSUE TITLE
Failed to build with v0.11.11

### ISSUE THREAD

**Issue by hden** [msgpack/msgpack-node#14]
Just a early warning before v0.12.x

```
> msgpack@0.2.2 install /Users/hden/Documents/development/node-serf/node_modules/msgpack
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.11.11/node-v0.11.11.tar.gz
gyp http 200 http://nodejs.org/dist/v0.11.11/node-v0.11.11.tar.gz
  CXX(target) Release/obj.target/libmsgpack/deps/msgpack/gcc_atomic.o
  CXX(target) Release/obj.target/libmsgpack/deps/msgpack/object.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  LIBTOOL-STATIC Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
In file included from /usr/include/arpa/inet.h:71:
/usr/include/netinet/in.h:302:2: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
        in_addr_t s_addr;
        ^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
In file included from /usr/include/arpa/inet.h:71:
/usr/include/netinet/in.h:377:2: error: unknown type name 'in_port_t'; did you
      mean 'node::in_port_t'?
        in_port_t       sin_port;
        ^
/usr/include/sys/_types/_in_port_t.h:30:21: note: 'node::in_port_t' declared
      here
typedef __uint16_t              in_port_t;
                                ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
In file included from /usr/include/arpa/inet.h:71:
In file included from /usr/include/netinet/in.h:654:
/usr/include/netinet6/in6.h:173:2: error: unknown type name 'in_port_t'; did you
      mean 'node::in_port_t'?
        in_port_t       sin6_port;      /* Transport layer port # (in_port_t) */
        ^
/usr/include/sys/_types/_in_port_t.h:30:21: note: 'node::in_port_t' declared
      here
typedef __uint16_t              in_port_t;
                                ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:75:1: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
in_addr_t        inet_addr(const char *);
^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:84:1: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
in_addr_t        inet_lnaof(struct in_addr);
^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:85:31: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
struct in_addr   inet_makeaddr(in_addr_t, in_addr_t);
                               ^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:85:42: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
struct in_addr   inet_makeaddr(in_addr_t, in_addr_t);
                                          ^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:86:1: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
in_addr_t        inet_netof(struct in_addr);
^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:87:1: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
in_addr_t        inet_network(const char *);
^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:23:
In file included from ../deps/msgpack/msgpack/object.h:21:
In file included from ../deps/msgpack/msgpack/zone.h:21:
In file included from ../deps/msgpack/msgpack/sysdep.h:65:
/usr/include/arpa/inet.h:90:19: error: unknown type name 'in_addr_t'; did you
      mean 'node::in_addr_t'?
char            *inet_neta(in_addr_t, char *, __darwin_size_t);
                           ^
/usr/include/sys/_types/_in_addr_t.h:30:20: note: 'node::in_addr_t' declared
      here
typedef __uint32_t      in_addr_t;      /* base type for internet address */
                        ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:25:
In file included from ../deps/msgpack/msgpack/pack.h:21:
In file included from ../deps/msgpack/msgpack/pack_define.h:23:
/usr/include/string.h:145:1: error: unknown type name 'errno_t'; did you mean
      'node::errno_t'?
errno_t memset_s(void *, rsize_t, int, rsize_t) __OSX_AVAILABLE_STARTING...
^
/usr/include/sys/_types/_errno_t.h:30:32: note: 'node::errno_t' declared here
typedef int                    errno_t;
                               ^
In file included from ../src/msgpack.cc:4:
In file included from ../deps/msgpack/msgpack.h:25:
In file included from ../deps/msgpack/msgpack/pack.h:21:
In file included from ../deps/msgpack/msgpack/pack_define.h:23:
/usr/include/string.h:145:26: error: C++ requires a type specifier for all
      declarations
errno_t memset_s(void *, rsize_t, int, rsize_t) __OSX_AVAILABLE_STARTING...
                         ^~~~~~~
/usr/include/string.h:145:40: error: unknown type name 'rsize_t'
errno_t memset_s(void *, rsize_t, int, rsize_t) __OSX_AVAILABLE_STARTING...
                                       ^
In file included from ../src/msgpack.cc:5:
In file included from /usr/include/c++/4.2.1/cmath:49:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:429:33: error: unknown type name 'gid_t'
int      chown(const char *, uid_t, gid_t);
                                    ^
/usr/include/unistd.h:444:1: error: unknown type name 'gid_t'
gid_t    getegid(void);
^
/usr/include/unistd.h:446:1: error: unknown type name 'gid_t'
gid_t    getgid(void);
^
/usr/include/unistd.h:450:21: error: C++ requires a type specifier for all
      declarations
int      getgroups(int, gid_t []);
                        ^~~~~
/usr/include/unistd.h:469:13: error: unknown type name 'gid_t'
int      setgid(gid_t);
                ^
/usr/include/unistd.h:565:34: error: unknown type name 'gid_t'
int      lchown(const char *, uid_t, gid_t) __DARWIN_ALIAS(lchown);
                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hden/.nodebrew/node/v0.11.11/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:879:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/Users/hden/.nodebrew/node/v0.11.11/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```
